IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'ForwardingStatus')
BEGIN
    ALTER TABLE GRA_CASES ADD ForwardingStatus NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'ClosureRemarks')
BEGIN
    ALTER TABLE GRA_CASES ADD ClosureRemarks NVARCHAR(1000) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'ClosureDate')
BEGIN
    ALTER TABLE GRA_CASES ADD ClosureDate DATETIME NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'OutwardNumber')
BEGIN
    ALTER TABLE GRA_CASES ADD OutwardNumber NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'OutwardDate')
BEGIN
    ALTER TABLE GRA_CASES ADD OutwardDate DATETIME NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'AdverseJudgmentPath')
BEGIN
    ALTER TABLE GRA_CASES ADD AdverseJudgmentPath NVARCHAR(MAX) NULL;
END
GO
