IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'AppealRemarks')
BEGIN
    ALTER TABLE GRA_CASES ADD AppealRemarks NVARCHAR(1000) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'AppealDate')
BEGIN
    ALTER TABLE GRA_CASES ADD AppealDate DATETIME NULL;
END
GO
