IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'LastDrawnBasic')
BEGIN
    ALTER TABLE GRA_CASES ADD LastDrawnBasic DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'LastDrawnBDA')
BEGIN
    ALTER TABLE GRA_CASES ADD LastDrawnBDA DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'LastDrawnBasic_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD LastDrawnBasic_CA DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'LastDrawnBDA_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD LastDrawnBDA_CA DECIMAL(18, 2) NULL;
END
GO
