IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'DeductionAmount')
BEGIN
    ALTER TABLE GRA_CASES ADD DeductionAmount DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'IsDeductionMade_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD IsDeductionMade_CA BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'DeductionDetails_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD DeductionDetails_CA NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'DeductionAmount_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD DeductionAmount_CA DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'ActualPaidAmount_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD ActualPaidAmount_CA DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'ChequeNumber_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD ChequeNumber_CA NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'ChequeDate_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD ChequeDate_CA DATETIME NULL;
END
GO
