IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'CopyDeliveredDate')
BEGIN
    ALTER TABLE GRA_CASES ADD CopyDeliveredDate DATETIME NULL;
END
GO
