IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'AppointmentDate_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD AppointmentDate_CA DATETIME NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'RetirementDate_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD RetirementDate_CA DATETIME NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'Period_SPE_LWA_ABS_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD Period_SPE_LWA_ABS_CA NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'LastDrawnPay_CA')
BEGIN
    ALTER TABLE GRA_CASES ADD LastDrawnPay_CA DECIMAL(18, 2) NULL;
END
GO
