IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'IsDocumentSent')
BEGIN
    ALTER TABLE GRA_CASES ADD IsDocumentSent BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'DocumentOutwardNo')
BEGIN
    ALTER TABLE GRA_CASES ADD DocumentOutwardNo NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'DocumentOutwardDate')
BEGIN
    ALTER TABLE GRA_CASES ADD DocumentOutwardDate DATETIME NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'IsObjectionFiled')
BEGIN
    ALTER TABLE GRA_CASES ADD IsObjectionFiled BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'ObjectionFiledDate')
BEGIN
    ALTER TABLE GRA_CASES ADD ObjectionFiledDate DATETIME NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'IsEvidenceFiled')
BEGIN
    ALTER TABLE GRA_CASES ADD IsEvidenceFiled BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'CurrentStage')
BEGIN
    ALTER TABLE GRA_CASES ADD CurrentStage NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GRA_CASES' AND COLUMN_NAME = 'NextHearingDate')
BEGIN
    ALTER TABLE GRA_CASES ADD NextHearingDate DATETIME NULL;
END
GO
