CREATE TABLE MVC_CASE_ADVERSE_DOCS (
    DocID INT PRIMARY KEY IDENTITY(1,1),
    CaseID INT NOT NULL,
    DocName NVARCHAR(MAX) NOT NULL,
    CONSTRAINT FK_MVC_CASE_ADVERSE_DOCS_CaseID FOREIGN KEY (CaseID) REFERENCES MVC_CASES(CaseID) ON DELETE CASCADE
);
GO
