-- Add Missing Columns to MVC_CASE_ADVERSE_DETAILS
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsBusCameraInstalled')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsBusCameraInstalled BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsCameraFootageProduced')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsCameraFootageProduced BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsPhotographProduced')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsPhotographProduced BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'PhotographNotProducedReason')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD PhotographNotProducedReason NVARCHAR(MAX) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'PoliceSketchExhibitNo')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD PoliceSketchExhibitNo NVARCHAR(50) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsPoliceSketchEnclosed')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsPoliceSketchEnclosed BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsEvidenceBasedOnSecurityReport')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsEvidenceBasedOnSecurityReport BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'SecurityReportNoEvidenceReason')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD SecurityReportNoEvidenceReason NVARCHAR(MAX) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsImpleadingAppFiled')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsImpleadingAppFiled BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'ImpleadingAppNotFiledReason')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD ImpleadingAppNotFiledReason NVARCHAR(MAX) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsVictimSalaried')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsVictimSalaried BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsIncomeCrossVerified')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsIncomeCrossVerified BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'DoesIncomeTallyWithDocuments')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD DoesIncomeTallyWithDocuments BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsAmountDepositedInEP')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsAmountDepositedInEP BIT NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'FutureProspectsPercentage')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD FutureProspectsPercentage DECIMAL(5, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'PersonalExpensesDeduction')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD PersonalExpensesDeduction DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'Multiplier')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD Multiplier DECIMAL(5, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfDependency')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD LossOfDependency DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfConsortium')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD LossOfConsortium DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfEstate')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD LossOfEstate DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'FuneralExpenses')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD FuneralExpenses DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfLoveAffection')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD LossOfLoveAffection DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'MedicalExpenseOther')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD MedicalExpenseOther DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'PainSufferings')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD PainSufferings DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'ConveyanceAttendant')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD ConveyanceAttendant DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfFutureIncome')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD LossOfFutureIncome DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfIncomeLaidUp')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD LossOfIncomeLaidUp DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfAmenities')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD LossOfAmenities DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'FutureMedicalExpenses')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD FutureMedicalExpenses DECIMAL(18, 2) NULL;
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'InjuryOtherExpense')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD InjuryOtherExpense DECIMAL(18, 2) NULL;
END
GO

-- Ensure MVC_CASE_ADVERSE_DOCS table exists
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DOCS')
BEGIN
    CREATE TABLE MVC_CASE_ADVERSE_DOCS (
        DocID INT PRIMARY KEY IDENTITY(1,1),
        CaseID INT NOT NULL,
        DocName NVARCHAR(MAX) NOT NULL,
        PageCount INT NULL, -- Add PageCount directly here
        CONSTRAINT FK_MVC_CASE_ADVERSE_DOCS_CaseID FOREIGN KEY (CaseID) REFERENCES MVC_CASES(CaseID) ON DELETE CASCADE
    );
END
ELSE
BEGIN
    -- If table exists, ensure PageCount column exists
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DOCS' AND COLUMN_NAME = 'PageCount')
    BEGIN
        ALTER TABLE MVC_CASE_ADVERSE_DOCS ADD PageCount INT NULL;
    END
END
GO
