-- Add new fields for EP filed and EP amount to MVC_CASE_ADVERSE_DETAILS table
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[MVC_CASE_ADVERSE_DETAILS]') AND name = 'IsEPFiled')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsEPFiled BIT NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[MVC_CASE_ADVERSE_DETAILS]') AND name = 'EPDepositedAmount')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD EPDepositedAmount DECIMAL(18, 2) NULL;
END
GO

-- Also update Remind Back table for consistency
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[MVC_REMIND_BACK_ADVERSE_DETAILS]') AND name = 'IsEPFiled')
BEGIN
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsEPFiled BIT NULL;
END
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[MVC_REMIND_BACK_ADVERSE_DETAILS]') AND name = 'EPDepositedAmount')
BEGIN
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD EPDepositedAmount DECIMAL(18, 2) NULL;
END
GO
