-- Ensure MVC_REMIND_BACK_ADVERSE_DETAILS has parity with MVC_CASE_ADVERSE_DETAILS
-- Run this on the target database to prevent data loss and ensure consistency

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsFIRFiledAgainstDriver')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsFIRFiledAgainstDriver BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsBusCameraInstalled')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsBusCameraInstalled BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsCameraFootageProduced')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsCameraFootageProduced BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsPhotographProduced')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsPhotographProduced BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'PhotographNotProducedReason')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD PhotographNotProducedReason NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'PoliceSketchExhibitNo')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD PoliceSketchExhibitNo NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsPoliceSketchEnclosed')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsPoliceSketchEnclosed BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsEvidenceBasedOnSecurityReport')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsEvidenceBasedOnSecurityReport BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'SecurityReportNoEvidenceReason')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD SecurityReportNoEvidenceReason NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsImpleadingAppFiled')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsImpleadingAppFiled BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'ImpleadingAppNotFiledReason')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD ImpleadingAppNotFiledReason NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsVictimSalaried')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsVictimSalaried BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsIncomeCrossVerified')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsIncomeCrossVerified BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'DoesIncomeTallyWithDocuments')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD DoesIncomeTallyWithDocuments BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsAmountDepositedInEP')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsAmountDepositedInEP BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'FutureProspectsPercentage')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD FutureProspectsPercentage DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'PersonalExpensesDeduction')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD PersonalExpensesDeduction DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'Multiplier')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD Multiplier DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfDependency')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD LossOfDependency DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfConsortium')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD LossOfConsortium DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfEstate')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD LossOfEstate DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'FuneralExpenses')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD FuneralExpenses DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfLoveAffection')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD LossOfLoveAffection DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'MedicalExpenseOther')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD MedicalExpenseOther DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'PainSufferings')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD PainSufferings DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'ConveyanceAttendant')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD ConveyanceAttendant DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfFutureIncome')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD LossOfFutureIncome DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfIncomeLaidUp')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD LossOfIncomeLaidUp DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'LossOfAmenities')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD LossOfAmenities DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'FutureMedicalExpenses')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD FutureMedicalExpenses DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'InjuryOtherExpense')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD InjuryOtherExpense DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsSTPassenger')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsSTPassenger BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsMedicalExpensesPaid')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsMedicalExpensesPaid BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'MedicalPaidAmount')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD MedicalPaidAmount DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'MedicalPaidRemarks')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD MedicalPaidRemarks NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsARFAmountPaid')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsARFAmountPaid BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'ARFPaidAmount')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD ARFPaidAmount DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'ARFPaidRemarks')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD ARFPaidRemarks NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsDelayApplicationFiled')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsDelayApplicationFiled BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'DelayApplicationPath')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD DelayApplicationPath NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsDelayCondonedAdverse')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsDelayCondonedAdverse BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'DelayCondonedOrderPath')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD DelayCondonedOrderPath NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsDeceasedInTR18')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD IsDeceasedInTR18 BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'MannerOfAccidentRO')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD MannerOfAccidentRO NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_RW' AND COLUMN_NAME = 'Designation')
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_RW ADD Designation NVARCHAR(MAX) NULL;

-- Create MVC_REMIND_BACK_ADVERSE_DOCS table if missing
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DOCS')
BEGIN
    CREATE TABLE MVC_REMIND_BACK_ADVERSE_DOCS (
        DocID INT PRIMARY KEY IDENTITY(1,1),
        RemindBackID INT NOT NULL,
        DocName NVARCHAR(MAX) NOT NULL,
        PageCount INT NULL,
        CONSTRAINT FK_MVC_REMIND_BACK_ADVERSE_DOCS_RBID FOREIGN KEY (RemindBackID) REFERENCES MVC_REMIND_BACK_CASES(RemindBackID) ON DELETE CASCADE
    );
END
GO
