-- Add CustomCompensation column for storing dynamic heads of compensation as JSON
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'CustomCompensation')
BEGIN
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD CustomCompensation NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_REMIND_BACK_ADVERSE_DETAILS' AND COLUMN_NAME = 'CustomCompensation')
BEGIN
    ALTER TABLE MVC_REMIND_BACK_ADVERSE_DETAILS ADD CustomCompensation NVARCHAR(MAX) NULL;
END
