IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LABOUR_CASES' AND COLUMN_NAME = 'LokAdalatDocumentPath')
BEGIN
    ALTER TABLE LABOUR_CASES ADD LokAdalatDocumentPath NVARCHAR(500) NULL;
END
GO
