-- Create table for storing and verifying OTPs for password reset
CREATE TABLE USER_OTP_VERIFICATIONS (
    VerificationID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT NOT NULL,
    OTP VARCHAR(10) NOT NULL,
    ExpiryTime DATETIME NOT NULL,
    IsVerified BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);

CREATE INDEX IX_USER_OTP_VERIFICATIONS_UserID ON USER_OTP_VERIFICATIONS(UserID);
CREATE INDEX IX_USER_OTP_VERIFICATIONS_OTP ON USER_OTP_VERIFICATIONS(OTP);
