-- Migration to move Case Progress fields to MVC_CASES table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'IsSTPassenger')
BEGIN
    ALTER TABLE MVC_CASES ADD IsSTPassenger BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'IsMedicalExpensesPaid')
BEGIN
    ALTER TABLE MVC_CASES ADD IsMedicalExpensesPaid BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'MedicalPaidAmount')
BEGIN
    ALTER TABLE MVC_CASES ADD MedicalPaidAmount DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'MedicalPaidRemarks')
BEGIN
    ALTER TABLE MVC_CASES ADD MedicalPaidRemarks NVARCHAR(500) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'IsARFAmountPaid')
BEGIN
    ALTER TABLE MVC_CASES ADD IsARFAmountPaid BIT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'ARFPaidAmount')
BEGIN
    ALTER TABLE MVC_CASES ADD ARFPaidAmount DECIMAL(18, 2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'ARFPaidRemarks')
BEGIN
    ALTER TABLE MVC_CASES ADD ARFPaidRemarks NVARCHAR(500) NULL;
END
GO
