-- Migration to fix missing columns that cause "Invalid column name" errors in Create Case
-- Run this on the target database (Admin_Law)

-- 1. FIX MVC_CASES (Primary Case Table)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'IsSTPassenger')
    ALTER TABLE MVC_CASES ADD IsSTPassenger BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'IsMedicalExpensesPaid')
    ALTER TABLE MVC_CASES ADD IsMedicalExpensesPaid BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'MedicalPaidAmount')
    ALTER TABLE MVC_CASES ADD MedicalPaidAmount DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'MedicalPaidRemarks')
    ALTER TABLE MVC_CASES ADD MedicalPaidRemarks NVARCHAR(500) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'IsARFAmountPaid')
    ALTER TABLE MVC_CASES ADD IsARFAmountPaid BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'ARFPaidAmount')
    ALTER TABLE MVC_CASES ADD ARFPaidAmount DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'ARFPaidRemarks')
    ALTER TABLE MVC_CASES ADD ARFPaidRemarks NVARCHAR(500) NULL;

-- 2. FIX MVC_CASE_ADVERSE_DETAILS (Adverse Award Table)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsSTPassenger')
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsSTPassenger BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsMedicalExpensesPaid')
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsMedicalExpensesPaid BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'MedicalPaidAmount')
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD MedicalPaidAmount DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'MedicalPaidRemarks')
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD MedicalPaidRemarks NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'IsARFAmountPaid')
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD IsARFAmountPaid BIT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'ARFPaidAmount')
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD ARFPaidAmount DECIMAL(18, 2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_DETAILS' AND COLUMN_NAME = 'ARFPaidRemarks')
    ALTER TABLE MVC_CASE_ADVERSE_DETAILS ADD ARFPaidRemarks NVARCHAR(MAX) NULL;

PRINT 'Migration successful: All missing columns added to MVC_CASES and MVC_CASE_ADVERSE_DETAILS.';
