IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('APPEAL_DETAILS') AND name = 'CorpMFAActionTakenPath')
BEGIN
    ALTER TABLE APPEAL_DETAILS ADD CorpMFAActionTakenPath NVARCHAR(MAX) NULL;
END
GO
