-- Migration for Third Party Registration Support
-- Adds missing columns to MVC_CASES and creates MVC_CASE_RESPONDENTS table

-- 1. Update MVC_CASES with Third Party specific fields
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'ClaimRemark')
    ALTER TABLE MVC_CASES ADD ClaimRemark NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'ClaimPetitionDate')
    ALTER TABLE MVC_CASES ADD ClaimPetitionDate DATE NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'HasInterimOrder')
    ALTER TABLE MVC_CASES ADD HasInterimOrder BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASES' AND COLUMN_NAME = 'InterimOrderFilePath')
    ALTER TABLE MVC_CASES ADD InterimOrderFilePath NVARCHAR(MAX) NULL;

-- 2. Create MVC_CASE_RESPONDENTS table (Section B of Third Party Form)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MVC_CASE_RESPONDENTS')
BEGIN
    CREATE TABLE MVC_CASE_RESPONDENTS (
        RespondentID INT PRIMARY KEY IDENTITY(1,1),
        CaseID INT NOT NULL,
        RespondentName NVARCHAR(500) NOT NULL,
        Remarks NVARCHAR(MAX) NULL,
        CreatedAt DATETIME DEFAULT GETDATE(),
        CONSTRAINT FK_MVC_CASE_RESPONDENTS_CaseID FOREIGN KEY (CaseID) REFERENCES MVC_CASES(CaseID) ON DELETE CASCADE
    );
END

-- 3. Ensure MVC_CASE_ADVERSE_PW has Remark and Designation columns if they don't exist
-- (Used for Respondent Evidence and Corporation Evidence in Third Party form)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_PW' AND COLUMN_NAME = 'Remark')
    ALTER TABLE MVC_CASE_ADVERSE_PW ADD Remark NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_ADVERSE_PW' AND COLUMN_NAME = 'Designation')
    ALTER TABLE MVC_CASE_ADVERSE_PW ADD Designation NVARCHAR(500) NULL;

PRINT 'Third Party Registration migration completed successfully.';
