-- Insert Data for Chikkodi Division
INSERT INTO [dbo].[MVC_DIVISION_ADVOCATES] (DivisionName, AdvocateName) VALUES 
('Chikkodi Division', N'A B Shintre'),
('Chikkodi Division', N'A G Huddar'),
('Chikkodi Division', N'A M Vantamuri'),
('Chikkodi Division', N'A R Kudalkar'),
('Chikkodi Division', N'B B Bislapur'),
('Chikkodi Division', N'B N Patil'),
('Chikkodi Division', N'B S Tavashi'),
('Chikkodi Division', N'C V Badri'),
('Chikkodi Division', N'D P Halappannavar'),
('Chikkodi Division', N'G S Bhat'),
('Chikkodi Division', N'L S Bandi'),
('Chikkodi Division', N'M A Hudli'),
('Chikkodi Division', N'M A Kakhandaki'),
('Chikkodi Division', N'M B Mastiholli'),
('Chikkodi Division', N'M B Patil'),
('Chikkodi Division', N'M G Patil'),
('Chikkodi Division', N'N M Yadavannavar'),
('Chikkodi Division', N'P B Madiwalar'),
('Chikkodi Division', N'R  G Tukkappanavar'),
('Chikkodi Division', N'R B Malli'),
('Chikkodi Division', N'S G Chougala'),
('Chikkodi Division', N'S M Patankar'),
('Chikkodi Division', N'S P Kamate'),
('Chikkodi Division', N'S R  Shinde'),
('Chikkodi Division', N'S S Angadi'),
('Chikkodi Division', N'B D Patil'),
('Chikkodi Division', N'V B Dhavaleshwar'),
('Chikkodi Division', N'V G B.Patil');

-- Insert Data for Bagalkot Division
INSERT INTO [dbo].[MVC_DIVISION_ADVOCATES] (DivisionName, AdvocateName) VALUES 
('Bagalkot Division', N'P B Madivalar'),
('Bagalkot Division', N'A G Huddar'),
('Bagalkot Division', N'A N Deshapande'),
('Bagalkot Division', N'A S Jagatap'),
('Bagalkot Division', N'A S Malipatil'),
('Bagalkot Division', N'B B Bisalapur'),
('Bagalkot Division', N'B B Saradesai'),
('Bagalkot Division', N'B R Kattimani'),
('Bagalkot Division', N'C Mahadevahi'),
('Bagalkot Division', N'C V Badari'),
('Bagalkot Division', N'C V Turamari'),
('Bagalkot Division', N'D S Bongale'),
('Bagalkot Division', N'G R Joshi'),
('Bagalkot Division', N'G V Joshi'),
('Bagalkot Division', N'Harish K B'),
('Bagalkot Division', N'J S Hiremath'),
('Bagalkot Division', N'Jayalalilata'),
('Bagalkot Division', N'K C Basavaraj'),
('Bagalkot Division', N'K C Shetty'),
('Bagalkot Division', N'K T Jambagi'),
('Bagalkot Division', N'K V Keruru'),
('Bagalkot Division', N'L D Kulkarani'),
('Bagalkot Division', N'M A Bidarakundi'),
('Bagalkot Division', N'M A Bijapur'),
('Bagalkot Division', N'M A Hudli'),
('Bagalkot Division', N'M A Kakhandaki'),
('Bagalkot Division', N'M A Patil'),
('Bagalkot Division', N'M B Patil'),
('Bagalkot Division', N'M C Anegundi'),
('Bagalkot Division', N'M G Patil'),
('Bagalkot Division', N'M I Katti'),
('Bagalkot Division', N'M M Tate'),
('Bagalkot Division', N'M V Ghooli'),
('Bagalkot Division', N'Mahadevayya'),
('Bagalkot Division', N'Mallikarjun Gooli'),
('Bagalkot Division', N'Manoraj'),
('Bagalkot Division', N'Meer Nadaf'),
('Bagalkot Division', N'N M Yadavannavar'),
('Bagalkot Division', N'N S Patil'),
('Bagalkot Division', N'Nagaraj Kamat'),
('Bagalkot Division', N'P A Jadava'),
('Bagalkot Division', N'P B Kuchabal'),
('Bagalkot Division', N'P R Tukkappanavar'),
('Bagalkot Division', N'R B Pawar'),
('Bagalkot Division', N'R G Tukkappanavar'),
('Bagalkot Division', N'R M Patil'),
('Bagalkot Division', N'R P Kumbar'),
('Bagalkot Division', N'S B Mathad'),
('Bagalkot Division', N'S D Kadi'),
('Bagalkot Division', N'S M Danappanavar'),
('Bagalkot Division', N'S R Hiremath'),
('Bagalkot Division', N'S S Aladakatti'),
('Bagalkot Division', N'S S Dongre'),
('Bagalkot Division', N'S S Jamagoudar'),
('Bagalkot Division', N'S S Mankani'),
('Bagalkot Division', N'S T Kamanalli'),
('Bagalkot Division', N'Sampuran ananda'),
('Bagalkot Division', N'Sujat  S Nidoni'),
('Bagalkot Division', N'V B Dhavaleshawar'),
('Bagalkot Division', N'V G Biradarapatil'),
('Bagalkot Division', N'V T Kulkarni'),
('Bagalkot Division', N'Veenapattanashety'),
('Bagalkot Division', N'Y F Niralakeri');
GO
