-- Add missing columns to LABOUR_CASES table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LABOUR_CASES' AND COLUMN_NAME = 'CO_Service_OutwardDate')
BEGIN
    ALTER TABLE LABOUR_CASES ADD CO_Service_OutwardDate DATETIME2;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LABOUR_CASES' AND COLUMN_NAME = 'CO_FurtherAppeal_DisposalOutwardNo')
BEGIN
    ALTER TABLE LABOUR_CASES ADD CO_FurtherAppeal_DisposalOutwardNo NVARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LABOUR_CASES' AND COLUMN_NAME = 'CO_FurtherAppeal_DisposalDate')
BEGIN
    ALTER TABLE LABOUR_CASES ADD CO_FurtherAppeal_DisposalDate DATETIME2;
END
GO
