CREATE TABLE LABOUR_CASE_VIEW_TRACKING (
    ViewID INT IDENTITY(1,1) PRIMARY KEY,
    CaseID INT NOT NULL,
    ViewedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_LabourView_Case FOREIGN KEY (CaseID) REFERENCES LABOUR_CASES(CaseID)
);
GO
