USE [Admin_Law]
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[admin_Law].[LABOUR_CONNECTED_CASES]') AND type in (N'U'))
BEGIN
    CREATE TABLE [admin_Law].[LABOUR_CONNECTED_CASES](
        [ConnectedCaseID] [int] IDENTITY(1,1) NOT NULL,
        [CaseID] [int] NOT NULL,
        [CaseDetails] [nvarchar](500) NULL,
        [FiledBy] [nvarchar](100) NULL,
        [CurrentStatus] [nvarchar](200) NULL,
     CONSTRAINT [PK_LABOUR_CONNECTED_CASES] PRIMARY KEY CLUSTERED 
    (
        [ConnectedCaseID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

    ALTER TABLE [admin_Law].[LABOUR_CONNECTED_CASES]  WITH CHECK ADD  CONSTRAINT [FK_LABOUR_CONNECTED_CASES_LABOUR_CASES] FOREIGN KEY([CaseID])
    REFERENCES [admin_Law].[LABOUR_CASES] ([CaseID])
    ON DELETE CASCADE

    ALTER TABLE [admin_Law].[LABOUR_CONNECTED_CASES] CHECK CONSTRAINT [FK_LABOUR_CONNECTED_CASES_LABOUR_CASES]
END
GO
