USE Admin_Law;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_CONNECTED' AND COLUMN_NAME = 'MACT')
BEGIN
    ALTER TABLE MVC_CASE_CONNECTED ADD MACT NVARCHAR(100) NULL;
    PRINT 'Added MACT column';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MVC_CASE_CONNECTED' AND COLUMN_NAME = 'IsDoubleClaim')
BEGIN
    ALTER TABLE MVC_CASE_CONNECTED ADD IsDoubleClaim BIT NOT NULL DEFAULT 0;
    PRINT 'Added IsDoubleClaim column';
END
GO
